name: Compiler Unit Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup GHC with stack
      uses: haskell/actions/setup@v1
      with:
        stack: 'true'
        ghc-version: 8.10.4
        stack-version: 2.5.1

    - name: Install dependencies
      run: stack setup

    - name: Build
      run: stack build

    - name: Unit Test
      run: stack test


