name: Compiler Unit Test

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup GHC with stack
      uses: haskell-actions/setup@v2
      with:
        ghc-version: 8.10.4
        enable-stack: true
        stack-version: 2.5.1

    - name: Install dependencies
      run: stack setup

    - name: Build
      run: stack build

    - name: Unit Test
      run: stack test


